[tool.poetry]
name = "yahoo"
version = "0.1.0"
description = ""
authors = ["Volker Lorrmann <volker.lorrmann@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.4"
requests = "^2.28.1"
numpy = "^1.23.2"
asyncio = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
