import pandas as pd
import requests

URLS = {
    "search": "https://query2.finance.yahoo.com/v1/finance/search",
    "searchAssist": "https://finance.yahoo.com/_finance_doubledown/api/resource/searchassist;searchTerm=",
    "validation": "https://query2.finance.yahoo.com/v6/finance/quote/validate",
    "quoteSummary": "https://query2.finance.yahoo.com/v10/finance/quoteSummary/",
    "quotes": "https://query2.finance.yahoo.com/v6/finance/quote",
    "chart": "https://query2.finance.yahoo.com/v8/finance/chart/",
    "lookup": "https://query1.finance.yahoo.com/v1/finance/lookup",
}

try:
    EXCHANGES = pd.read_html(
        requests.get("https://help.yahoo.com/kb/SLN2310.html").text
    )[0]
except:
    pass

ALL_MODULES = {
    # 'assetProfile',
    "assetProfile": {
        "key": None,
        "convert": "s",
        "convert_dates": ["governanceEpochDate", "compensationAsOfEpochDate"],
    },
    "balanceSheetHistory": {
        "key": "balanceSheetStatements",
        "convert": "df",
        "convert_dates": ["endDate"],
    },
    "balanceSheetHistoryQuarterly": {
        "key": "balanceSheetStatements",
        "convert": "df",
        "convert_dates": ["endDate"],
    },
    "calendarEvents": {
        "key": "earnings",
        "convert": "s",
        "convert_dates": ["earningsDate"],
    },
    "cashflowStatementHistory": {
        "key": "cashflowStatements",
        "convert": "df",
        "convert_dates": ["endDate"],
    },
    "cashflowStatementHistoryQuarterly": {
        "key": "cashflowStatements",
        "convert": "df",
        "convert_dates": ["endDate"],
    },
    "defaultKeyStatistics": {
        "key": None,
        "convert": "s",
        "convert_dates": [
            "sharesShortPreviousMonthDate",
            "dateShortInterest",
            "lastFiscalYearEnd",
            "nextFiscalYearEnd",
            "fundInceptionDate",
            "lastSplitDate",
            "mostRecentQuarter",
            "lastDividendDate",
        ],
    },
    "earnings": {"key": None, "convert": "df", "convert_dates": ["earningsDate"]},
    "earningsHistory": {
        "key": "history",
        "convert": "df",
        "convert_dates": ["quarter"],
    },
    "earningsTrend": {"key": "trend", "convert": "df", "convert_dates": ["date"]},
    "financialData": {"key": None, "convert": "s", "convert_dates": []},
    "fundOwnership": {
        "key": "ownershipList",
        "convert": "df",
        "convert_dates": ["reportDate"],
    },
    "incomeStatementHistory": {
        "key": "incomeStatementHistory",
        "convert": "df",
        "convert_dates": ["endDate"],
    },
    "incomeStatementHistoryQuarterly": {
        "key": "incomeStatementHistory",
        "convert": "df",
        "convert_dates": ["endDate"],
    },
    # 'indexTrend',
    # 'industryTrend',
    "insiderHolders": {
        "key": "holders",
        "convert": "df",
        "convert_dates": ["latestTransDate", "positionDirectDate"],
    },
    "insiderTransactions": {
        "key": "transactions",
        "convert": "df",
        "convert_dates": ["startDate"],
    },
    "institutionOwnership": {
        "key": "ownershipList",
        "convert": "df",
        "convert_dates": ["reportDate"],
    },
    "majorHoldersBreakdown": {"key": None, "convert": "s", "convert_dates": []},
    "netSharePurchaseActivity": {
        "key": None,
        "convert": "s",
        "convert_dates": [],
    },
    "price": {
        "key": None,
        "convert": "s",
        "convert_dates": ["preMarketTime", "regularMarketTime", "postMarketTime"],
    },
    "quoteType": {
        "key": None,
        "convert": "s",
        "convert_dates": ["firstTradeDateEpochUtc"],
    },
    "recommendationTrend": {
        "key": "trend",
        "convert": "df",
        "convert_dates": [],
    },
    # 'sectorTrend',
    "summaryDetail": {
        "key": None,
        "convert": "s",
        "convert_dates": ["exDividendDate", "expireDate", "startDate"],
    },
    "summaryProfile": {"key": None, "convert": "s", "convert_dates": []},
}

QUOTE_SUMMARY_COLUMNS = [
    "52_week_change",
    "beta",
    "book_value",
    "buy_info_count",
    "buy_info_shares",
    "buy_percent_insider_shares",
    "country",
    "currency",
    "currency_symbol",
    "current_price",
    "current_ratio",
    "date_short_interest",
    "debt_to_equity",
    "dividend_rate",
    "earnings_estimate_+1q_avg",
    "earnings_estimate_+1q_growth",
    "earnings_estimate_+1q_high",
    "earnings_estimate_+1q_low",
    "earnings_estimate_+1q_number_of_analysts",
    "earnings_estimate_+1q_year_ago_eps",
    "earnings_estimate_+1y_avg",
    "earnings_estimate_+1y_growth",
    "earnings_estimate_+1y_high",
    "earnings_estimate_+1y_low",
    "earnings_estimate_+1y_number_of_analysts",
    "earnings_estimate_+1y_year_ago_eps",
    "earnings_estimate_+5y_avg",
    "earnings_estimate_+5y_growth",
    "earnings_estimate_+5y_high",
    "earnings_estimate_+5y_low",
    "earnings_estimate_+5y_number_of_analysts",
    "earnings_estimate_+5y_year_ago_eps",
    "earnings_estimate_-5y_avg",
    "earnings_estimate_-5y_growth",
    "earnings_estimate_-5y_high",
    "earnings_estimate_-5y_low",
    "earnings_estimate_-5y_number_of_analysts",
    "earnings_estimate_-5y_year_ago_eps",
    "earnings_estimate_0q_avg",
    "earnings_estimate_0q_growth",
    "earnings_estimate_0q_high",
    "earnings_estimate_0q_low",
    "earnings_estimate_0q_number_of_analysts",
    "earnings_estimate_0q_year_ago_eps",
    "earnings_estimate_0y_avg",
    "earnings_estimate_0y_growth",
    "earnings_estimate_0y_high",
    "earnings_estimate_0y_low",
    "earnings_estimate_0y_number_of_analysts",
    "earnings_estimate_0y_year_ago_eps",
    "ebitda",
    "ebitda_margins",
    "enterprise_to_ebitda",
    "enterprise_to_revenue",
    "enterprise_value",
    "eps_actual_-1q",
    "eps_actual_-2q",
    "eps_actual_-3q",
    "eps_actual_-4q",
    "eps_difference_-1q",
    "eps_difference_-2q",
    "eps_difference_-3q",
    "eps_difference_-4q",
    "eps_estimate_-1q",
    "eps_estimate_-2q",
    "eps_estimate_-3q",
    "eps_estimate_-4q",
    "exchange",
    "exchange_data_delayed_by",
    "exchange_name",
    "float_shares",
    "forward_eps",
    "forward_pe",
    "free_cashflow",
    "gross_margins",
    "gross_profits",
    "held_percent_insiders",
    "held_percent_institutions",
    "implied_shares_outstanding",
    "industry",
    "insiders_percent_held",
    "institutions_count",
    "institutions_float_percent_held",
    "institutions_percent_held",
    "last_fiscal_year_end",
    "last_split_factor",
    "market_cap",
    "most_recent_quarter",
    "net_income_to_common",
    "net_info_count",
    "net_info_shares",
    "net_percent_insider_shares",
    "next_fiscal_year_end",
    "number_of_analyst_opinions",
    "operating_cashflow",
    "operating_margins",
    "price_to_book",
    "price_to_sales_trailing12_months",
    "profit_margins",
    "quick_ratio",
    "recommendation_key",
    "recommendation_mean",
    "return_on_assets",
    "return_on_equity",
    "revenue_estimate_+1q_avg",
    "revenue_estimate_+1q_growth",
    "revenue_estimate_+1q_high",
    "revenue_estimate_+1q_low",
    "revenue_estimate_+1q_number_of_analysts",
    "revenue_estimate_+1q_year_ago_revenue",
    "revenue_estimate_+1y_avg",
    "revenue_estimate_+1y_growth",
    "revenue_estimate_+1y_high",
    "revenue_estimate_+1y_low",
    "revenue_estimate_+1y_number_of_analysts",
    "revenue_estimate_+1y_year_ago_revenue",
    "revenue_estimate_+5y_avg",
    "revenue_estimate_+5y_growth",
    "revenue_estimate_+5y_high",
    "revenue_estimate_+5y_low",
    "revenue_estimate_+5y_number_of_analysts",
    "revenue_estimate_+5y_year_ago_revenue",
    "revenue_estimate_-5y_avg",
    "revenue_estimate_-5y_growth",
    "revenue_estimate_-5y_high",
    "revenue_estimate_-5y_low",
    "revenue_estimate_-5y_number_of_analysts",
    "revenue_estimate_-5y_year_ago_revenue",
    "revenue_estimate_0q_avg",
    "revenue_estimate_0q_growth",
    "revenue_estimate_0q_high",
    "revenue_estimate_0q_low",
    "revenue_estimate_0q_number_of_analysts",
    "revenue_estimate_0q_year_ago_revenue",
    "revenue_estimate_0y_avg",
    "revenue_estimate_0y_growth",
    "revenue_estimate_0y_high",
    "revenue_estimate_0y_low",
    "revenue_estimate_0y_number_of_analysts",
    "revenue_estimate_0y_year_ago_revenue",
    "revenue_growth",
    "revenue_per_share",
    "sand_p52_week_change",
    "sector",
    "sell_info_count",
    "sell_info_shares",
    "sell_percent_insider_shares",
    "shares_outstanding",
    "shares_percent_shares_out",
    "shares_short",
    "shares_short_previous_month_date",
    "shares_short_prior_month",
    "short_name",
    "short_percent_of_float",
    "short_ratio",
    "surprise_percent_-1q",
    "surprise_percent_-2q",
    "surprise_percent_-3q",
    "surprise_percent_-4q",
    "symbol",
    "target_high_price",
    "target_low_price",
    "target_mean_price",
    "target_median_price",
    "time_zone_full_name",
    "total_cash",
    "total_cash_per_share",
    "total_debt",
    "total_insider_shares",
    "total_revenue",
    "trailing_eps",
    "trailing_pe",
]


COUNTRIES = {
    "france": {"lang": "fr-FR", "region": "FR", "corsDomain": "fr.finance.yahoo.com"},
    "india": {"lang": "en-IN", "region": "IN", "corsDomain": "in.finance.yahoo.com"},
    "hong kong": {
        "lang": "zh-Hant-HK",
        "region": "HK",
        "corsDomain": "hk.finance.yahoo.com",
    },
    "germany": {"lang": "de-DE", "region": "DE", "corsDomain": "de.finance.yahoo.com"},
    "canada": {"lang": "en-CA", "region": "CA", "corsDomain": "ca.finance.yahoo.com"},
    "spain": {"lang": "es-ES", "region": "ES", "corsDomain": "es.finance.yahoo.com"},
    "italy": {"lang": "it-IT", "region": "IT", "corsDomain": "it.finance.yahoo.com"},
    "united states": {
        "lang": "en-US",
        "region": "US",
        "corsDomain": "finance.yahoo.com",
    },
    "australia": {
        "lang": "en-AU",
        "region": "AU",
        "corsDomain": "au.finance.yahoo.com",
    },
    "united kingdom": {
        "lang": "en-GB",
        "region": "GB",
        "corsDomain": "uk.finance.yahoo.com",
    },
    "brazil": {"lang": "pt-BR", "region": "BR", "corsDomain": "br.financas.yahoo.com"},
    "new zealand": {
        "lang": "en-NZ",
        "region": "NZ",
        "corsDomain": "nz.finance.yahoo.com",
    },
    "singapore": {
        "lang": "en-SG",
        "region": "SG",
        "corsDomain": "sg.finance.yahoo.com",
    },
    "taiwan": {"lang": "zh-tw", "region": "TW", "corsDomain": "tw.finance.yahoo.com"},
}
